sudo: false
language: python
matrix:
  include:
  - os: linux
    env: NAME=format
    python: '3.6'
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep yapf | xargs pip install
    script: check/format-incremental
  - os: linux
    env: NAME=pylint
    python: '3.6'
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep pylint | xargs pip install
    script: check/pylint
  - os: linux
    env: NAME=pytest-and-incremental-coverage
    python: '3.6'
    install:
      - python -m pip install -r requirements.txt
      - python -m pip install -r examples/requirements.txt
      - python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest-and-incremental-coverage master --actually-quiet
  - os: linux
    python: "2.7"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=2.7
  - os: linux
    python: "3.4"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.4
  - os: linux
    python: "3.5"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.5
  - os: linux
    python: "3.6"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.6

before_install:
  - pip$PY install --upgrade pip setuptools wheel

install:
  - if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
  - pip$PY install pytest
  - pip$PY install pytest-cov
  - pip$PY install coveralls
  - pip$PY install sphinx
  - pip$PY install sphinx_rtd_theme
  - pip$PY install -e .

script: sphinx-build -nW -b html -d docs/_build/doctrees/ docs/ docs/_build/html
script: export OMP_NUM_THREADS=1 && pytest src/openfermion --cov src/openfermion

after_success:
  - coveralls
